services:
  - type: web
    name: hardik-rent-backend
    runtime: node
    repo: https://github.com/Engineerrobin7/Hardik-Rent.git
    rootDir: hardik_rent_backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
