services:
  - type: web
    name: hardik-rent-backend
    runtime: docker
    branch: main
    region: oregon
    rootDir: hardik_rent_backend
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 3000