name: hardik_rent_backend
description: A server for the Hardik Rent app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^0.13.3
  lints: ^2.0.0
  test: ^1.16.0
